version: '3'

services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-go:stable-1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    networks:
      - backend
    
  mongodb:
    image: mongo
    container_name: mongodb   
    ports:
      - "27017:27017"
    restart: unless-stopped       
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p4ssw0rd
    volumes:
      - ./mongo-data:/data/db
    networks:
      backend:
        ipv4_address: 172.20.0.10
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express    
    ports:
      - "8080:8081"
    restart: unless-stopped       
    networks:
      - backend
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=p4ssw0rd
      - ME_CONFIG_MONGODB_SERVER=mongodb
networks:
      backend:
        name: backend
        ipam:
          driver: default
          config:
            - subnet: 172.20.0.0/16
