version: '3'
services:
  valhalla:
    image: akrck02/valhalla-core:latest
    container_name: valhalla-core-dev
    restart: always
    ports:
      - 3333:3333
    volumes:
      - ../../api:/compile
      - ./cache:/cache
    networks:
      - valhalla-dev

networks:
      valhalla-dev:
        name: valhalla-dev
        ipam:
          driver: default
          config:
            - subnet: ${MASK_MONGODB}
